name: Bug Report
description: Report a problem with Azemmur components
title: ${{ inputs.issue_title }}
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please provide as much detail as possible so we can reproduce and fix the issue quickly.
  - type: input
    id: title
    attributes:
      label: Issue Title
      description: A concise title summarizing the problem.
      placeholder: e.g., Button hover animation breaks on Safari
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the issue that you are encountering, and how other people can reproduce it.
      placeholder: |
        Reproduction steps...
    validations:
      required: true
  - type: textarea
    id: code_example
    attributes:
      label: Code example
      description: Provide an example code snippet that demonstrates the problem.
      placeholder: |
        ```tsx
        <Button onClick={() => {}}>Click me</Button>
        ```
  - type: input
    id: component
    attributes:
      label: Concerned component
      description: The component that you are experiencing the issue with.
      placeholder: Button
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate, like browser, OS, or version details.
